# Jeremiah Wilson
# jeremiah.james.wilson@gmail.com

# Config
set -g default-terminal "screen-256color" # force 256 color support
# set -g mouse on # enable mouse selecting panes

# Keybinds
# Remap prefix to Ctrl-`
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Move panes with Ctrl+Vim keys
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

# Split panes with - and |
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
