version = 3
[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  [[blocks.segments]]
    template = 'root <#ebdbb2>in</> '
    foreground = '#fabd2f'
    type = 'root'
    style = 'plain'
  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#fe8019'
    type = 'path'
    style = 'plain'
    [blocks.segments.properties]
      style = 'folder'
  [[blocks.segments]]
    template = '<#ebdbb2>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = '#d3869b'
    type = 'git'
    style = 'plain'
    [blocks.segments.properties]
      fetch_status = true
  [[blocks.segments]]
    template = '<#ebdbb2>via</>  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
    foreground = '#b8bb26'
    type = 'node'
    style = 'plain'
    [blocks.segments.properties]
      fetch_version = true
  [[blocks.segments]]
    template = 'x '
    foreground = '#cc241d'
    type = 'status'
    style = 'plain'
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  [[blocks.segments]]
    template = "\n➜ "
    foreground = '#b8bb26'
    type = 'text'
    style = 'plain'
[transient_prompt]
  foreground = '#b8bb26'
  background = 'transparent'
  template = '➜ '
